<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7MO5Bq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7MO5Bq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7MO5Bq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7MO5Bq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX7MO5Bq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X7MO5Bq',
    'container.build_id' => '81b7d97c',
    'container.build_time' => 1550206873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7MO5Bq');
